#!/bin/bash

cd ~/planc/build/
make || exit

cd ~/planc/build/dense_hiernmf
mpirun -n 4 ./dense_hiernmf -a 7 -i ~/planc/hiernmf/4cores/Arows -d "16 16" -p "4 1" -k 4 -t 500 -e 1 > ~/planc/hiernmf/dense

#cd ~/planc/build/sparse_hiernmf
#mpirun -n 1 ./sparse_hiernmf -a 7 -i rand_lowrank -d "16 16" -p "1 1" -k 2 -t 500 -e 1 -s 0.9 > ~/planc/hiernmf/sparse

